# .gitlab-ci.yml

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node:12
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

test:
  stage: test
  image: node:12
  script:
    - npm install
    - npm run test

deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t myapp:$CI_COMMIT_SHORT_SHA .
    - docker tag myapp:$CI_COMMIT_SHORT_SHA myapp:latest
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push myapp:$CI_COMMIT_SHORT_SHA
    - docker push myapp:latest
  only:
    - master
