# Example Woodpecker CI yaml file for a typical Hexo site

pipeline:
  # Build step: it generates the files for the Hexo site
  build:
    image: node:lts-alpine
    commands:
      - cd src
      - npm install hexo-cli -g
      - test -e package.json && npm install
      - hexo generate
      - cd ..
    when:
      branch:
        # Only run on these branches
        include: [ main ]
        # ...and never on pages branch (to ignore build triggered by CI commits)
        exclude: pages
      # Execute on every event except "pull_request"
      event: [push, tag, deployment]

  # Push step: it pushes the build output to "pages" branch
  push:
    image: appleboy/drone-git-push
    settings:
      branch: pages
      remote: git@codeberg.org:hexo-test/pages.git
      # To work around "rejected...fetch first" error
      force: true
      commit: true
      commit_message: "Woodpecker build ${CI_COMMIT_SHA:0:7}"
      # Replace with your username for the commit
      author_name: "adnan360"
      # Replace with your email for the commit
      author_email: "adnan360@protonmail.com"
      ssh_key:
        from_secret: ssh_key
    when:
      # Only try to commit if previous step is successful
      status: success
      branch:
        # Only run on these branches
        include: [ main ]
        # ...and never on pages branch (to ignore build triggered by CI commits)
        exclude: pages
      # Execute on every event except "pull_request"
      event: [push, tag, deployment]
